<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Dotnet Core 3.1 on Coding notes</title>
    <link>https://www.bustroker.com/tags/dotnet-core-3.1/</link>
    <description>Recent content in Dotnet Core 3.1 on Coding notes</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>en-us</language>
    <lastBuildDate>Tue, 05 May 2020 00:00:00 +0000</lastBuildDate>
    <atom:link href="https://www.bustroker.com/tags/dotnet-core-3.1/index.xml" rel="self" type="application/rss+xml" />
    <item>
      <title>Handling parallel exceptions in dotnet</title>
      <link>https://www.bustroker.com/notes/handling-parallel-exceptions-in-dotnet/</link>
      <pubDate>Tue, 05 May 2020 00:00:00 +0000</pubDate>
      <guid>https://www.bustroker.com/notes/handling-parallel-exceptions-in-dotnet/</guid>
      <description>I&amp;rsquo;m executing several tasks in parallel, where more than one throw exceptions. I want to handle all the exceptions, which basically means catching them all and being able to, at least, rethrowing them with all the info they carry.&#xA;So, here it is how&#xA;var runnersTasks = new List&amp;lt;Task&amp;gt;();// list to keep the tasks created Task compositeTask = null; // task consisting in waiting for all the tasks to finish in parallel try { // run all the tasks and keep them in the list Runners.</description>
    </item>
  </channel>
</rss>
